root = "data/kittiobj3d"

train_set_ratio = 0.7
valid_set_ratio = 0.3

proj_img_h = 128
proj_img_w = 1024

cls_weight = [0.7, 0.6, 0.8, 0.3, 0.7, 0.7, 0.8, 0.8, 0.8]

kitti_obj3d_det_cls_names = [
    "DontCare", # 0.7
    "Car", # 0.6
    "Cyclist", # 0.8
    "Misc", # 0.3
    "Pedestrian", # 0.7
    "Person_sitting", # 0.7
    "Tram", # 0.8
    "Truck", # 0.8
    "Van", # 0.8
]

label_field_name_list = [
    "object_type",
    "truncation",
    "occlusion",
    "alpha",
    "left",
    "top",
    "right",
    "bottom",
    "height",
    "width",
    "length",
    "x",
    "y",
    "z",
    "rotation_y",
]

[pallete]
	DontCare = [0, 0, 0]
	Car = [255, 0, 0]
	Cyclist = [0, 255, 0]
	Pedestrian = [0, 0, 255]
	Misc = [255, 255, 0]
	Person_sitting = [255, 0, 255]
	Tram = [0, 255, 255]
	Truck = [255, 128, 0]
	Van = [0, 128, 255]
