root = "data/partanno"

used_class = "Airplane"

train_set_ratio = 0.7
valid_set_ratio = 0.3

voxel_size = 0.025

proj_img_h = 32
proj_img_w = 32

proj_axis_list = [
	[0, 1, 1],
	[1, 0, 1],
	[1, 1, 0],
	[0, -1, -1],
	[-1, 0, -1],
	[-1, -1, 0],
	[1, 1, 1],
	[-1, -1, -1]
]

cls_names = [
	"Airplane",
	"Bag",
	"Cap",
	"Car",
	"Chair",
	"Earphone",
	"Guitar",
	"Knife",
	"Lamp",
	"Laptop",
	"Motorbike",
	"Mug",
	"Pistol",
	"Rocket",
	"Skateboard",
	"Table"
]

selected_cls_name = "Airplane"

[syn2cls]
	02691156 = "Airplane"
	02773838 = "Bag"
	02954340 = "Cap"
	02958343 = "Car"
	03001627 = "Chair"	
	03261776 = "Earphone"
	03467517 = "Guitar"	
	03624134 = "Knife"	
	03636649 = "Lamp"
	03642806 = "Laptop"	
	03790512 = "Motorbike"	
	03797390 = "Mug"
	03948459 = "Pistol"	
	04099429 = "Rocket"	
	04225987 = "Skateboard" 	
	04379243 = "Table"	

[seqs_split]
	train = 0.7
	valid = 0.2
	testt = 0.1
