root = "partanno"

used_class = "Airplane"

train_set_ratio = 0.7
valid_set_ratio = 0.3

proj_img_h = 128
proj_img_w = 128

cls_names = [
	"Airplane",
	"Bag",
	"Cap",
	"Car",
	"Chair",
	"Earphone",
	"Guitar",
	"Knife",
	"Lamp",
	"Laptop",
	"Motorbike",
	"Mug",
	"Pistol",
	"Rocket",
	"Skateboard",
	"Table"
]

[syn2cls]
	Airplane 	= "02691156"
	Bag 		= "02773838"
	Cap 		= "02954340"
	Car 		= "02958343"
	Chair 		= "03001627"
	Earphone 	= "03261776"
	Guitar 		= "03467517"
	Knife 		= "03624134"
	Lamp 		= "03636649"
	Laptop 		= "03642806"
	Motorbike 	= "03790512"
	Mug 		= "03797390"
	Pistol 		= "03948459"
	Rocket 		= "04099429"
	Skateboard 	= "04225987"
	Table 		= "04379243"
