root = "data/kittiobj3d"

train_set_ratio = 0.7
valid_set_ratio = 0.3

proj_img_w = 512
proj_img_h = 64

kitti_obj3d_det_cls_names = [
    "DontCare",
    "Car",
    "Cyclist",
    "Misc",
    "Pedestrian",
    "Person_sitting",
    "Tram",
    "Truck",
    "Van",
]

label_field_name_list = [
    "object_type",
    "truncation",
    "occlusion",
    "alpha",
    "left",
    "top",
    "right",
    "bottom",
    "height",
    "width",
    "length",
    "x",
    "y",
    "z",
    "rotation_y",
]

[pallete]
	DontCare = [0, 0, 0]
	Car = [255, 0, 0]
	Cyclist = [0, 255, 0]
	Pedestrian = [0, 0, 255]
	Misc = [255, 255, 0]
	Person_sitting = [255, 0, 255]
	Tram = [0, 255, 255]
	Truck = [255, 128, 0]
	Van = [0, 128, 255]
