kitti_obj3d_det_cls_names: [
    "DontCare",
    "Car",
    "Cyclist",
    "Misc",
    "Pedestrian",
    "Person_sitting",
    "Tram",
    "Truck",
    "Van"
]

label_field_name_list: [
    "object_type",
    "truncation",
    "occlusion",
    "alpha",
    "left", "top", "right", "bottom",
    "height", "width", "length",
    "x", "y", "z",
    "rotation_y"
]

train_set_ratio: 0.7
valid_set_ratio: 0.3

proj_img_w: 512
proj_img_h: 64

ignore_cls: 0
bg_clsname: "DontCare"
batch_size: 4
