exp_name = "deeplabv3+kittisem"

[model]
	name = "DeepLabV3"
	conf = "conf/model/DeepLabV3.toml"

[dataset]
	name = "KITTISemantic"
	conf = "conf/dataset/KITTISemantic.toml"

[loss]
	name = "DeepLabV3Loss"
	conf = "conf/loss/DeepLabV3Loss.toml"

[metric]
	name = "DeepLabV3Metric"
	conf = "conf/metric/DeepLabV3Metric.toml"

[log]
	log_interv = 10
	log_alldir = "log/test"

[train]
	lr = 0.001
	batch_size = 4
	num_epochs = 10
