exp_name = "kittiobj3d+deeplabv3"

[model]
	name = "DeepLabV3"
	conf = "conf/model/model_deeplabv3.toml"

[dataset]
	name = "KITTIObj3d"
	conf = "conf/dataset/dataset_kittiobj3d.toml"

[loss]
	name = "DeepLabV3Loss"
	conf = "conf/loss/loss_deeplabv3.toml"

[metric]
	name = "DeepLabV3Metric"
	conf = "conf/metric/metric_deeplabv3.toml"

[log]
	log_alldir = "log/test"
	log_interv = 10

[train]
	lr = 0.001
	batch_size = 8
	num_epochs = 50
