exp_name = "squeezeseg+kittiobj3d"

[model]
	name = "SqueezeSeg"
	conf = "conf/model/model_squeezeseg.toml"

[dataset]
	name = "KITTIObj3d"
	conf = "conf/dataset/dataset_kittiobj3d.toml"

[loss]
	name = "SqueezeSegLoss"
	conf = "conf/loss/loss_squeezeseg.toml"

[metric]
	name = "SqueezeSegMetric"
	conf = "conf/metric/metric_squeezeseg.toml"

[log]
	log_alldir = "log/test"
	log_interv = 10

[train]
	lr = 0.001
	batch_size = 16
	num_epochs = 50
