exp_name: "deeplabv3+kittiobj3d"

model:
  cls_name: "DeepLabV3"
  conf_yaml: "conf/model/DeepLabV3.yaml"

dataset:
  cls_name: "KITTIObj3d"
  conf_yaml: "conf/dataset/KITTIObj3d.yaml"

loss:
  cls_name: "DeepLabV3Loss"
  conf_yaml: "conf/loss/DeepLabV3Loss.yaml"

metric:
  cls_name: "DeepLabV3Metric"
  conf_yaml: "conf/metric/DeepLabV3Metric.yaml"

log:
  log_interv: 10
  log_alldir: "log/test"

train:
  lr: 0.001
  batch_size: 8
  num_epochs: 50
